### ISSUE TITLE
Looks like maybe some access checking isn't done in edit_onecontact.cgi

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-registrar#1]
All of the other edit forms have some stuff that seems to be checking for access and providing errors. This one doesn't. It does try to use $d at the end of the file, so I've defined it here:

https://github.com/virtualmin/virtualmin-registrar/blob/master/edit_onecontact.cgi#L13

But, I have vague feelings that if all the other edit forms have some checking at the top, this one should too?

**Comment by jcameron** [comment]
Yeah, a check is missing. I'll add it.
