### ISSUE TITLE
$account is undefined in find_registrar_account in virtualmin-registrar-lib.pl

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-registrar#3]
In this line:

https://github.com/virtualmin/virtualmin-registrar/blob/master/virtualmin-registrar-lib.pl#L91

What is now $dname was $account, which was undefined in this function. Looking at the similar functions that use $account, it looks like a copy-paste error, and that $dname should be what's there, instead. I've changed that, but, because I can't easily test it, I wanted to confirm with you.

**Comment by jcameron** [comment]
Actually, it should have been $a . I'll check in a fix.
