### ISSUE TITLE
$msg undefined, I think it should be $id

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-registrar#4]
In this line:

https://github.com/virtualmin/virtualmin-registrar/blob/master/virtual_feature.pl#L118

I changed $msg to $id, based on contextual clues about what's supposed to be happening...but, I might be wrong. It originally used $msg, but $msg is undefined in that scope, so it was never going to be right. So, either $msg needs defining, or it's supposed to be $id. I guessed $id. Holler if that's wrong.

**Comment by jcameron** [comment]
$id is correct
